### PR TITLE
[Minor]  Updating and consolidating Github Action versioning

### PR DESCRIPTION
**Pull request by TelicentPaul**
I started out updating some Github action versions to address warnings in build pipeline but thought I should do a more thorough job and have updated all the github actions that were out of date. 
More importantly, I have consolidated the versioning so that the actions are all on same versioning in order to  provide consistency across workflows.

Also, fixed a spelling mistake and formatting a table too. 

There are obviously some major version bumps here..... _but_.... the versioning approach taken seems a little slip-shod so it should be fine. Obviously it's something to keep an eye on just in case. 

For those actions using "@master" I've just left alone although common advice is to use specific versions (despite the obvious hassle) to avoid issues cropping up that could take an age to diagnose. Most seem to be our own files which is understandable.

### CODE REVIEW

**Review by gnikolov95 — COMMENTED** [review]
One thing to note is using the following `uses: actions/setup-java@v4`, it will automatically use the latest release of that major version. Unless we need specific version I would suggest we do not pin the versions with the following: `uses: actions/setup-java@v4.4.0`.
 
 Just update the dependencies to latest major version e.g from v3 to v4, also some of these could have major changes in them which break functionality, I could go through them when I have the time - appreciate for taking the initiative to update those because they've been on my radar for awhile as well.

**Comment by TelicentPaul** [comment]
> One thing to note is using the following `uses: actions/setup-java@v4`, it will automatically use the latest release of that major version. Unless we need specific version I would suggest we do not pin the versions with the following: `uses: actions/setup-java@v4.4.0`. 

That's not technically always the case.  It depends on the tagging strategy used on the relevant lib. 

I'm happy if you want any of the python touching stuff to be reverted - it can be picked up later. I like to be proactive and improve the repos when I can. I've also added dependabot so that will help do things in smaller iterations going forward.

**Comment by gnikolov95** [comment]
>>
> That's not technically always the case. It depends on the tagging strategy used on the relevant lib.
> 
> I'm happy if you want any of the python touching stuff to be reverted - it can be picked up later. I like to be proactive and improve the repos when I can. I've also added dependabot so that will help do things in smaller iterations going forward.

That is a very good point, didn't cross my mind at all. I was thinking about the more common ones we use but some in fact don't. Thanks, just ignore the comment then. Plus we also have dependabot now. The python ones can stay it is totally fine.

**Comment by ACoolmanTelicent** [comment]
I don't mind what we do - but if we are in the bleeding edge of minor/patches - then we are fine if everything is working as intended.

<details>
 <summary>Tangent</summary>
 
If some bad actor wants to do a supply chain attack ...well its just a risk we need to be mindful of. We should doc and treat this as the start of the discussion that suites us now, and leave it open to exact pinning (or other strategies) when/iif it suits.

</details>

**Review by rvesse — APPROVED** [review]

**Review by ACoolmanTelicent — APPROVED** [review]

**Pull request merged**
